host:
  secret: "faputa"
  port: 5000
  debug: True
web:
  theme: "mdui"
  title: "Status Sosu!"
  mdui-primary-color: "indigo"
client:
  demo:
    name: "Nanachi"
    note: "naaaaaa"
    system:
      display: True
      custom: "Custom system name"
    processor:
      display: True
      custom: "Custom CPU name"
    machine:
      display: True
      custom: "DMA66"
    cpu-usage:
      display: True
      show-frequency: True
      show-cores: True
    mem-usage:
      display: True
      show-detail: True
    swap-usage:
      display: True
      show-detail: True
    disk:
      display: True
      show-detail: True
    network:
      display: True
  test:
    name: "Another test server"
    note: "let it go"
    system:
      display: True
      custom: "Better than nothing"
    processor:
      display: True
      custom: ""
    machine:
      display: False
      custom: ""
    cpu-usage:
      display: True
      show-frequency: True
      show-cores: True
    mem-usage:
      display: True
      show-detail: True
    swap-usage:
      display: True
      show-detail: True
    disk:
      display: False
      show-detail: True
    network:
      display: True

    